name             'neuron-network-caffe'
maintainer       'glmanhtu'
maintainer_email 'glmanhtu@gmail.com'
license          'All rights reserved'
description      'Automatic install caffe for python'
version          '0.1.0'
depends 'poise-python'